openapi: 3.0.3
info:
  title: Swagger System Metrics - OpenAPI 3.0
  description: This is a sample System Metrics API developed for HPDA course
  termsOfService: http://swagger.io/terms/
  contact:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
    email: syedshameersarwar@gmail.com
  version: 1.0.11
servers:
- url: http://127.0.0.1:8080/api
tags:
- name: metric
  description: Basic System Metrics
paths:
  /metric:
    get:
      tags:
      - metric
      summary: Get all metrics
      description: Get all metrics
      operationId: get_all_metrics
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Metric'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Metric'
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.metric_controller
    put:
      tags:
      - metric
      summary: Update an existing metric
      description: Update an existing metric by Id
      operationId: update_metric
      requestBody:
        description: Update an existent metric in the DB
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Metric'
          application/xml:
            schema:
              $ref: '#/components/schemas/Metric'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Metric'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Metric'
            application/xml:
              schema:
                $ref: '#/components/schemas/Metric'
        "400":
          description: Invalid ID supplied
        "404":
          description: Metric not found
        "405":
          description: Validation exception
      x-openapi-router-controller: swagger_server.controllers.metric_controller
    post:
      tags:
      - metric
      summary: Add a new metric to the DB
      description: Add a new metric to the DB
      operationId: add_metric
      requestBody:
        description: Create a new metric in the DB
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Metric'
          application/xml:
            schema:
              $ref: '#/components/schemas/Metric'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Metric'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Metric'
            application/xml:
              schema:
                $ref: '#/components/schemas/Metric'
        "405":
          description: Invalid input
      x-openapi-router-controller: swagger_server.controllers.metric_controller
  /metric/{metricId}:
    get:
      tags:
      - metric
      summary: Find metric by ID
      description: Returns a single metric
      operationId: get_metric_by_id
      parameters:
      - name: metricId
        in: path
        description: ID of metric to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Metric'
            application/xml:
              schema:
                $ref: '#/components/schemas/Metric'
        "400":
          description: Invalid ID supplied
        "404":
          description: Metric not found
      x-openapi-router-controller: swagger_server.controllers.metric_controller
    post:
      tags:
      - metric
      summary: Updates a metric in the DB with form data
      description: ""
      operationId: update_metric_with_form
      parameters:
      - name: metricId
        in: path
        description: ID of metric that needs to be updated
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: cpu_model
        in: query
        description: Cpu Model of metric that needs to be updated
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: cpu_cores
        in: query
        description: Number of Cpu Cores of metric that needs to be updated
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      - name: ram_capacity
        in: query
        description: RAM Capacity of metric that needs to be updated
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "405":
          description: Invalid input
      x-openapi-router-controller: swagger_server.controllers.metric_controller
    delete:
      tags:
      - metric
      summary: Deletes a Metric
      description: delete a Metric
      operationId: delete_metric
      parameters:
      - name: metricId
        in: path
        description: Metric id to delete
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid ID supplied
        "404":
          description: Metric not found
      x-openapi-router-controller: swagger_server.controllers.metric_controller
components:
  schemas:
    Metric:
      required:
      - cpu_cores
      - cpu_model
      - ram_capacity
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        cpu_model:
          type: string
          example: Intel
        cpu_cores:
          type: integer
          format: int64
          example: 8
        ram_capacity:
          type: string
          example: 8 GB
      example:
        cpu_model: Intel
        ram_capacity: 8 GB
        cpu_cores: 8
        id: 10
      xml:
        name: metric
  requestBodies:
    Metric:
      description: Metric object that needs to be added to the DB
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Metric'
        application/xml:
          schema:
            $ref: '#/components/schemas/Metric'

